[package]
name = "crap"
version = "0.2.5"
edition = "2021"
repository = "https://github.com/JustJam-Dev/CRApp"

[dependencies]
eframe = "0.28"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "macros", "chrono", "migrate"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
image = "0.24"
tiktoken-rs = "0.5"
egui_extras = { version = "0.28", features = ["image", "all_loaders"] }
rfd = "0.17.1"
base64 = "0.21"
png = "0.17"
arboard = "3.4"
rusqlite = { version = "0.32", features = ["bundled"] }
url = "2.5.8"
uuid = { version = "1.0", features = ["v4"] }
zspell = { version = "0.5", features = ["unstable-suggestions"] }
zip = "0.6"
walkdir = "2"
self_update = { version = "0.41", features = ["archive-zip", "compression-zip-deflate"] }
imageproc = "0.23.0"
rusttype = "0.9"
html-escape = "0.2"
egui_cosmic_text = "0.2"

# Force enable features for the version of image used by egui_extras
image_v25 = { package = "image", version = "0.25", features = ["jpeg", "png"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
tracing-appender = "0.2.5"
anyhow = "1.0.102"
thiserror = "2.0.18"
