use crate::models::Lorebook;
use crate::ui::CrapApp;
use eframe::egui;

pub fn render_lorebook_characters(app: &mut CrapApp, ui: &mut egui::Ui, book: &Lorebook) {
    // --- Linked Characters Gallery ---
    ui.heading(format!("Characters Linked to '{}'", book.title));
    ui.add_space(8.0);

    let mut browser_actions = Vec::new();
    let all_colls = app.collections.clone(); // Clone for immutable access to collections inside loop

    // Filter characters
    let linked_chars: Vec<crate::models::Character> = app
        .characters
        .iter()
        .filter(|c| {
            if let Some(links) = app.char_lore_map.get(&c.id) {
                links.contains(&book.id)
            } else {
                false
            }
        })
        .cloned()
        .collect();

    if linked_chars.is_empty() {
        ui.label("No characters linked to this Lorebook.");
        ui.label("Go to a Character -> Lorebooks tab to link them.");
    } else {
        egui::ScrollArea::vertical()
            .id_source("lore_chars_scroll")
            .show(ui, |ui| {
                ui.horizontal_wrapped(|ui| {
                    for char in &linked_chars {
                        crate::ui::views::browser::render_character_card(
                            ui,
                            char,
                            &all_colls,
                            &mut browser_actions,
                            app.blur_all_images,
                            app.blur_all_nsfw,
                            app.blur_mode,
                            &app.blur_overrides,
                        );
                    }
                });
            });
    }

    // Handle Browser Actions generated by cards
    for action in browser_actions {
        match action {
            crate::ui::browser::BrowserAction::MoveCharacter(char_id, target_id) => {
                app.move_character(char_id, target_id);
            }
            crate::ui::browser::BrowserAction::ToggleFavorite(char_id) => {
                app.toggle_favorite(char_id);
            }
            crate::ui::browser::BrowserAction::DeleteCharacter(id) => {
                let name = app
                    .characters
                    .iter()
                    .find(|c| c.id == id)
                    .map(|c| c.name.clone())
                    .unwrap_or_default();
                app.popup_state = crate::ui::PopupState::DeleteCharacterConfirmation { id, name };
            }
            crate::ui::browser::BrowserAction::RenameCollection(id, name) => {
                app.popup_state = crate::ui::PopupState::Renaming { id, name };
            }
            crate::ui::browser::BrowserAction::DeleteCollection(id) => {
                app.delete_collection(id); // Simple delete call, ignoring complex warning logic for now or reusing if precise
            }
            crate::ui::browser::BrowserAction::CreateCharacter(cid) => {
                app.create_new_character(cid);
            }
            crate::ui::browser::BrowserAction::CreateCollection(cid) => {
                app.save_collection(0, "New Folder".to_string(), cid);
            }
            crate::ui::browser::BrowserAction::UpdateCollectionIcon(id) => {
                app.popup_state = crate::ui::PopupState::CollectionIconConfirmation {
                    id,
                    path: String::new(),
                    _preview_texture: None,
                };
            }
            crate::ui::browser::BrowserAction::OpenCharacter(id) => {
                // CRITICAL: Restore lorebook ownership before navigation
                // The lorebook editor took ownership via .take(), so app.selected_lorebook is None.
                // We need to restore it before load_character() calls push_history(),
                // otherwise the history won't capture the lorebook ID.
                app.selected_lorebook = Some(book.clone());
                app.load_character(id);
            }
            crate::ui::browser::BrowserAction::OpenCollection(_) => {}
            crate::ui::browser::BrowserAction::ExportCollection(_) => {}
            crate::ui::browser::BrowserAction::ShowStatistics(_) => {}
            crate::ui::browser::BrowserAction::ToggleBlur(id) => {
                app.toggle_character_blur(id);
            }
        }
    }
}
